### PR TITLE
 Add collect_symbols to the default pipelines and store symbols in resources

### PR DESCRIPTION
**Pull request by keshav-space**
- fixes https://github.com/nexB/purldb/issues/323

### CODE REVIEW

**Review by JonoYang — CHANGES_REQUESTED** [review]
@keshav-space The PR looks good, I have a couple of notes:

- It doesn't look like `merge_or_create_resource` merges data, but just overwrites the existing values on the Resource with new values. (https://github.com/nexB/purldb/blob/main/minecode/model_utils.py#L428) In the case where we have an existing Resource with symbol data stored in the `extra_data` field, the contents of the `extra_data` field will be overwritten if the incoming Resource data has values in there. I think it would make sense to append the new `extra_data` to the existing one instead of overwriting it, but I wanted to know what you think.

- We should have a test for `merge_or_create_resource` to make sure that the `extra_data` field is updated.

**Comment by keshav-space** [comment]
> * It doesn't look like `merge_or_create_resource` merges data, but just overwrites the existing values on the Resource with new values. (https://github.com/nexB/purldb/blob/main/minecode/model_utils.py#L428) In the case where we have an existing Resource with symbol data stored in the `extra_data` field, the contents of the `extra_data` field will be overwritten if the incoming Resource data has values in there. I think it would make sense to append the new `extra_data` to the existing one instead of overwriting it, but I wanted to know what you think.

@JonoYang  We could append data, but wouldn't that be more confusing? Suppose we already have `source_symbols` in the resource. If we reindex this package with a new version of `source_inspector` I don't think it would make sense to append this to the existing `source_symbols`.

**Comment by JonoYang** [comment]
> @JonoYang We could append data, but wouldn't that be more confusing? Suppose we already have `source_symbols` in the resource. If we reindex this package with a new version of `source_inspector` I don't think it would make sense to append this to the existing `source_symbols`.

That's a good point. I think it would be good to rename `merge_or_create_resource` to `update_or_create_resource` and remove the `merged` variable in the function.

**Comment by keshav-space** [comment]
@JonoYang I've renamed the `merge_or_create_resource` and also added the test.

**Review by JonoYang — APPROVED** [review]
@keshav-space Looks good, thanks!

**Pull request merged**
